### ISSUE TITLE
Multiline comments get a blank line in-between.

### ISSUE THREAD

**Issue by dadgar** [hashicorp/hcl#108]
When formatting HCL via the printer:
```
	# Priority controls our access to resources and scheduling priority.
	# This can be 1 to 100, inclusively, and defaults to 50.
	# priority = 50
```
becomes:
```
  # Priority controls our access to resources and scheduling priority.


  # This can be 1 to 100, inclusively, and defaults to 50.


  # priority = 50
```

**Comment by sethvargo** [comment]
Hi @dadgar 

When does this happen? Is this with the HCL writer? What command are you running?

**Comment by dadgar** [comment]
Hey, it is in the printer library. Experiencing it when using `hclfmt` https://github.com/fatih/hclfmt/issues/7

**Comment by sethvargo** [comment]
I'm experiencing a version of this too. Given:

```hcl
  # These two arguments use outputs from another module. The ssh_keys module
  # we have been using outputs the key name and key path. The Consul module
  # takes those values as arguments.
  key_name = "${aws_key_pair.hashicorp-training.key_name}"
  private_key_path = "${path.module}/${var.private_key_path}"
```

the formatter is doing this:

```hcl
  # These two arguments use outputs from another module. The ssh_keys module
  # we have been using outputs the key name and key path. The Consul module
  # takes those values as arguments.
  key_name = "${aws_key_pair.hashicorp-training.key_name}"

  private_key_path = "${path.module}/${var.private_key_path}"
```

It should really be doing this:

```hcl
  # These two arguments use outputs from another module. The ssh_keys module
  # we have been using outputs the key name and key path. The Consul module
  # takes those values as arguments.
  key_name         = "${aws_key_pair.hashicorp-training.key_name}"
  private_key_path = "${path.module}/${var.private_key_path}"
```

which is what it does if there's only a single-line comment:

```hcl
  # These two arguments use outputs from another module. The ssh_keys module
  key_name         = "${aws_key_pair.hashicorp-training.key_name}"
  private_key_path = "${path.module}/${var.private_key_path}"
```

/cc @jen20

**Comment by grubernaut** [comment]
@sethvargo I've already implemented a fix for this, https://github.com/hashicorp/hcl/pull/113

**Comment by dangerp** [comment]
I'm not terribly familiar with Go, but it appears that each comment line is being treated as a separate standalone comment.  If there is no blank line between the multiline comment and the next resource,  the comment is untouched as expected.  A temporary workaround is to use the hcl multiline comment syntax, as I mentioned in https://github.com/hashicorp/terraform/issues/6375#issuecomment-215202169.

**Comment by dangerp** [comment]
Here's a simple diff for getting a failing test reproducing the issue: https://gist.github.com/dangerp/6fe9a5f300979ba3b5244377a93ac44f.  I can take a stab at a fix later, but my go skills are non-existent so that may not work out :)

**Comment by mitchellh** [comment]
This is now fixed!

**Comment by majormoses** [comment]
@mitchellh still seeing this

**Comment by majormoses** [comment]
@mitchellh you can disregard it was fixed after bumping some dependencies on my end...sorry for the spam...
