### ISSUE TITLE
Is there a style guide?

### ISSUE THREAD

**Issue by tjsingleton** [hashicorp/hcl#111]
I was wondering if there is a style guide for hcl. I found this, https://github.com/bsnape/terraform-style-guide, but don't know if it represents the community or not.

**Comment by sethvargo** [comment]
Hi @tjsingleton 

I don't think there is an official styleguide, but there is an HCL writer which will format the HCL code to what we believe is the proper style and format. 

There's also: 

- https://github.com/fatih/vim-hclfmt
- https://github.com/fatih/hclfmt

The author there is actually the author of the current version of the HCL parser and writer as well.

Here is a generally-rough styleguide:

```
//                     v brace MUST appear at end of first line of block
resource "type" "name" {
  // <-- indents MUST be two spaces
  an_attribute      = "value"
  another_attribute = "another_value"
  third_attribute   = "three"
  //                ^ equals for adjacent attributes SHOULD be aligned

  // ^ empty lines MAY be used to separate attributes into logical groups
  subblock {
    one   = "foo"
    two   = "bar"
    three = "qux"
    // ^^ attribute ordering not dictated, users MAY choose alpha or any other semantic ordering
  }
}
```

Please let me know if you have any questions.

**Comment by tjsingleton** [comment]
@sethvargo thanks!

**Comment by oryband** [comment]
@sethvargo any chance to add a `STYLE.md` or something that will *officialize* this?
