### ISSUE TITLE
Support backtick quoted raw string literals

### ISSUE THREAD

**Issue by samuelhug** [hashicorp/hcl#122]
What are your guys' thoughts on adding support for backtick quoted string literals and treating them as raw, not doing any escaping. Similar to what golang does.

I know there is the HEREDOC, but for one-liner shell scripts and queries I feel the backtick quoted string is better suited.

I did a quick and dirty implementation of this the other day, and I would be willing to refine it if its something other people would like as well.

**Comment by mitchellh** [comment]
I'm not against this but I currently don't want to introduce new syntax in the configuration. Sorry!

**Comment by tmccombs** [comment]
The absence of something like this is especially annoying when writing Regular expressions. See also https://github.com/hashicorp/terraform/issues/24604.
