### ISSUE TITLE
Provide HCL Marshaler

### ISSUE THREAD

**Issue by Smuerdt** [hashicorp/hcl#124]
Are there plans to provide a HCL marshaler? I had a lot of situation where I would prefer an auto generated hcl over an auto generated json.

**Comment by sethvargo** [comment]
Hi @Smuerdt 

HCL does have a writer https://github.com/hashicorp/hcl/tree/master/hcl/printer

**Comment by kvz** [comment]
Hey there as @sethvargo mentioned, you can use the HCL printer (and `terraform fmt`) to do this now. @acconut and I took the liberty of wrapping a few of HashiCorp's libraries and release `json2hcl` (and hcl2json via `-reverse`) binaries for this. In the offchance this is still useful to somebody: https://github.com/kvz/json2hcl
