### ISSUE TITLE
Question: fuzzing?

### ISSUE THREAD

**Issue by BrianHicks** [hashicorp/hcl#126]
I've found a bunch of invalid inputs that make the HCL parser panic using `go-fuzz` and the following program, using `test-fixtures` as the corpus:

```go
package fuzzy

import "github.com/hashicorp/hcl"

// Fuzz does go-fuzz work
func Fuzz(data []byte) int {
	if len(data) == 0 {
		return -1
	}

	if _, err := ParseSafely(data); err != nil {
		return 0
	}

	return 1
}

// ParseSafely does what it says on the tin
func ParseSafely(buf []byte) (out interface{}, err error) {
	return out, hcl.Unmarshal(buf, &out)
}
```

I'm happy to share my corpus output (it found ~381 crashing inputs in about 20 minutes). Would this be helpful, and are y'all interested in using the results of such an analysis?

**Comment by jen20** [comment]
Hi @BrianHicks! @phinze and I were actually discussing applying property testing to HCL just yesterday, so this is great timing! I'm definitely interested in your results, and in building this form of testing into HCL (and HIL) for the future.

**Comment by BrianHicks** [comment]
OK, I'll try to tease the errors I got into a few categories and open up separate errors for them, if that's alright? I don't want to spam y'all. :)

**Comment by BrianHicks** [comment]
Opened #127 and #128. These are the main two error messages I'm seeing so far.

**Comment by BrianHicks** [comment]
Added #129 and #130. These four errors seem to be "unique"[1] out of the 462 I was able to generate. I stopped the fuzzing when the error rate reached 1 out of every 100 calls.

[1]: unique with regards to call site, as far as I can tell. These last two are formatted messages that include the bad input, and I was deduplicating based on panic messages.

**Comment by mitchellh** [comment]
I'm going to close this since you've opened other issues. I'm still open to adding fuzzing directly to the unit test suite but would be willing to use a PR for that. Otherwise, will address your findings one at a time (+ unit test).

**Comment by BrianHicks** [comment]
Sounds like a plan, thanks. I'll do more fuzzing as the issues get closed out. I'm not real clear on how to integrate go-fuzz into CI, but surely it's possible!

**Comment by BrianHicks** [comment]
(er, I say that to say: if I knew what would work, I would totally submit a PR)
