### ISSUE TITLE
Parsing invalid duration at the close of a block is clipped to nanoseconds...

### ISSUE THREAD

**Issue by sean-** [hashicorp/hcl#131]
When parsing a Nomad job file, we noticed there was a grammar error when parsing a service check that made use of the `mapstructure.StringToTimeDurationHookFunc` decode hook.  Using the two inputs:

```
// This is valid input
      service {
	  timeout = "10s"
	  interval = "10s"
        }
```

vs

```
// This validates, but parses to the wrong value (10ns vs 1e10ns)
      service {
	  timeout = "10s"
	  interval = 10s
        }
```

The first snippet's interval would correctly return an interval of 1e10 nanoseconds, whereas the second snippet would return only 10 nanoseconds.  If we changed the HCL file to parse the interval before the timeout, the HCL parser would correctly detect that interval was not a valid string.  e.g.

```
      service {
	  interval = 10s
	  timeout = "10s"
        }
```

I haven't had a chance to put together a test, but it's likely an interaction between HCL's tokenizer and mapstructure's decoder.

https://github.com/hashicorp/nomad/blob/master/jobspec/parse.go#L335-L346

CC @dadgar

**Comment by mitchellh** [comment]
I took your exact text and put it in a test case and it produced a parser error:

```
Error: key 's' expected start of object ('{') or assignment ('=')
```

I'm guessing you're missing something or Nomad may be using an outdated HCL?
