### ISSUE TITLE
HCL Parser ignores errors

### ISSUE THREAD

**Issue by leventyalcin** [hashicorp/hcl#142]
Hi everyone, 

I'm not sure how I'm gonna tell this but I think there is some regression on HCL parser. It ignores some errors. 

I've tried with 0.6.16, 0.7.0-rc2 and 0.7.0, but the result is same all the time. 

Let me show you with an example; 

```
 leoman  /tmp/a  1  terraform -version
Terraform v0.7.0

 leoman  /tmp/a  cat m.tf
variale "t1" { default = "levent" }
variale "t2" { default = "t2" }
variale "t3" { default = "t3" }

output "test" {
  value = "${join(",", list( var.t1, var.t2, var.t3))}"
}
 leoman  /tmp/a  terraform apply
Error configuring: 3 error(s) occurred:

* output.test: missing dependency: var.t1
* output.test: missing dependency: var.t2
* output.test: missing dependency: var.t3
```
it didn't complain about typo with `variable/variale`.

When I do some typo with `output` it shows all the errors. 

```
 leoman  /tmp/a  1  sed -i.bak 's/output/outut/g' m.tf
 leoman  /tmp/a  cat m.tf
variale "t1" { default = "levent" }
variale "t2" { default = "t2" }
variale "t3" { default = "t3" }

outut "test" {
  value = "${join(",", list( var.t1, var.t2, var.t3))}"
}
 leoman  /tmp/a  terraform apply
There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Errors:

  * 1 error(s) occurred:

* module root: 4 error(s) occurred:

* Unknown root level key: variale
* Unknown root level key: variale
* Unknown root level key: variale
* Unknown root level key: outut
 leoman  /tmp/a  1 
```

Cheers, 
Levent.

**Comment by fatih** [comment]
Hi @leventyalcin 

I think you should open this issue to the terraform repo. I'm not sure this is a HCL based problem. `output` or `variable` are not HCL specific keywords. In fact there are no such keywords. For `HCL` they are just string identifier tokens.

**Comment by leventyalcin** [comment]
Hi @fatih, 

I was trying to figure out who is defining the tokens but Go is still confusing me a lot. I'll close this and create an issue in terraform repo. 

Thanks anyway.
