### ISSUE TITLE
Feature request:  better multi-line string formatting

### ISSUE THREAD

**Issue by adampats** [hashicorp/hcl#144]
Coming from a terraform perspective, I have noticed that code readability deteriorates when column lengths get really long.  This problem tends to crop-up frequently with argument string values inside resources, and unfortunately the current syntax options (HEREDOC or newlines inside interpolation functions) are limiting.  I'm still learning the internals of HCL, but I think one / both of the following options might work for this:

1)  Multi-line string literal with white-space trimming.  Similar to the Python triple-quote ("""):

```hcl
tags {
  Name = """${var.foo}-${var.bar}-
            my-application-elb-${var.baz}"""
}
```

2)  String concatenation operators (and a new-line escape like bash?), similar to (how I do it) in Python:

```hcl
tags {
  Name = "${var.foo}-${var.bar}-" + \
         "my-application-elb-${var.baz}"
}
```

See previous issue under terraform for background:
https://github.com/hashicorp/terraform/issues/8210

Thoughts?

**Comment by mitchellh** [comment]
This is now possible with a heredoc with `-`: 

```
<<FOO-
  hello
  there
FOO
```

This will trim spaces up to the first <

**Comment by kvz** [comment]
Trying to use this now in Terraform 0.9.6, I think maybe this HCL patch hasn't landed there yet? I'm getting `At 1:53: invalid characters in heredoc anchor` but when I remove the dash from `FOO-`, it works as 'expected' (executes without errors, but whitespace is preserved)

**Comment by apparentlymart** [comment]
Hi @kvz,

I think there is a mistake in the earlier example. The dash actually belongs _before_ the identifier, like this:

```hcl
<<-FOO
  hello
  there
FOO
```

Sorry about that...

**Comment by kvz** [comment]
Thanks for the quick help!

This gives me `At 11:1: heredoc not terminated` but when I remove the `-`, things work.

**Comment by apparentlymart** [comment]
:thinking: I'm not sure what's going on, @kvz. Would you mind opening a new top-level issue and sharing some more details/examples of what you're trying?

**Comment by avoidik** [comment]
Sample use-case to execute with `terraform apply`

```
# test.tf
variable "blah" {
  type = "string"
}
output "test" {
  value = "${var.blah}"
}
```

Test case 1 - does not work

```
# terraform.tfvars
blah = <<-EOF
test
test
EOF
```

Error is

```
Error parsing terraform.tfvars: At 6:1: heredoc not terminated
```

Test case 2 - does not work

```
# terraform.tfvars
blah = <<EOF-
test
test
EOF
```

Error is

```
Error parsing terraform.tfvars: At 2:13: invalid characters in heredoc anchor
```

**Comment by avoidik** [comment]
@apparentlymart @mitchellh could you please clarify approach to conjoin multi-line strings into single line-string with heredoc?

**Comment by BlaineAtAffirm** [comment]
Btw, in case anyone comes by this later, the example that worked for me was
```
variable "boolean_var" {
  description = <<-HERE
                verbose text
                even more text
                woah, that's quite the explanation there
-HERE
  default = "false"
}
```

(though this breaks emacs syntax highlighting atm)

**Comment by slmingol** [comment]
In TF 0.11.11 this worked without issue:

```
output "key_fingerprint" {
  value = <<-EOF
        ${aws_iam_access_key.OktaSSOUser.key_fingerprint}
  EOF
}
```

**Comment by fosskers** [comment]
Ah looks like `<<-` breaks Emacs' `terraform-mode` again :sweat:
