### ISSUE TITLE
Printer adds superfluous newlines(?)

### ISSUE THREAD

**Issue by kvz** [hashicorp/hcl#148]
Hi, we're trying to run Printer and we're getting superfluous newlines like so:

```hcl
"provider" "aws" {
  "access_key" "${var.FREY_AWS_ACCESS_KEY}"

  "region" "us-east-1"

  "secret_key" "${var.FREY_AWS_SECRET_KEY}"
}

"resource" "aws_dynamodb_table" "basic-dynamodb-table" {
  "hash_key" "UserId"

  "name" "GameScores"

  "range_key" "GameTitle"

  "read_capacity" 20

  "write_capacity" 20

  "attribute" {
    "name" "TopScore"

    "type" "N"
  }
```

Looking at the code it seems these two newlines cause it: https://github.com/hashicorp/hcl/blob/master/hcl/printer/nodes.go#L144 

It seems this was done for a reason but we're unsure which one that is?

**Comment by mitchellh** [comment]
This is fixed with #149
