### ISSUE TITLE
Inconsistent parse errors on empty map element

### ISSUE THREAD

**Issue by brianshumate** [hashicorp/hcl#158]
### HCL Template
```hcl
## Port mapping 
port_map {
tcp_1988 = 1988
tcp_8888 = 8888
tcp_8989 = 8989
stats =
}
```

### Expected behavior
Error parsing job file due to an empty map element

### Actual behavior

Error parsing job file does actually occur when the empty `stats` element is the *first one* in the map, but does not occur when it is the last element in the map as shown in the above example.

### Steps to reproduce
1. Create a job file in HCL
2. Place a map in the job file like the example with an empty element
3. Observe the output of validation (in my case using `nomad validate example.hcl`) with the empty map element in starting and ending positions

**Comment by mitchellh** [comment]
Got a fix in a PR. Thanks!

**Comment by brianshumate** [comment]
👍 Awesome, thank you!

**Comment by achilu** [comment]
thanks @brianshumate
