### ISSUE TITLE
Emacs mode?

### ISSUE THREAD

**Issue by tv42** [hashicorp/hcl#18]
It would be nice to have an emacs code that can keep indentation right, etc. Anyone use emacs? Is some pre-existing mode a good enough match?

**Comment by grubernaut** [comment]
There's an HCL mode for emacs on melpa as well https://github.com/syohex/emacs-hcl-mode

**Comment by tv42** [comment]
The emacs libraries mentioned look good; if anything, it'd be nice for Terraform docs to point to them. This bug seems "done enough".
