### ISSUE TITLE
Require external files

### ISSUE THREAD

**Issue by mytototo** [hashicorp/hcl#187]
Hey,

I'm writing a Go program that needs a configuration file wrote in HCL. This configuration file can be messy or very hard to read if there is a lot of configuration.

Is there any way to require/import file and assign it to a specific key? Or is there a way to merge HCL files with Go?

Thanks.

**Comment by apparentlymart** [comment]
Hi @mytototo,

I see that you closed this issue but I thought I would answer your question anyway in case it's useful to someone else in the future:

HCL itself does not have built-in features for requiring one file from another. This sort of functionality is generally implemented within the calling application itself, which allows different levels of abstraction.  For example, in Terraform (arguably the most prolific HCL user) we load all of the files in one directory and merge them in a Terraform-specific way, and also allow users to declare "modules" which allow collections  of configuration to be retrieved from external sources and used not as lexical includes but as an entirely different namespace of configuration.

Generally HCL parsing is just the first step of a configuration-loading pipeline, and we expect that features such as merging multiple files or including one into another will be handled in a later, application-specific step.
