### ISSUE TITLE
Fails to parse time.Duration

### ISSUE THREAD

**Issue by dc0d** [hashicorp/hcl#202]
### HCL Template
```hcl
App {
    PostponeExit = 5s
}
```

### Expected behavior
It should be able to parse Go-style time duration.

### Actual behavior
With a struct like:
```go
type Conf struct {
	App struct {
		PostponeExit time.Duration
	}

	// ...
}
```
We have to use a value 5000000000 to get a 5s duration. If we use `5s` as value in `hcl` file, we get:
```
At 3:9: nested object expected: LBRACE got: ASSIGN
```
And if we use a string like `"5s"`, we get:
```
strconv.ParseInt: parsing "5s": invalid syntax
```

I saw issues related to this. But they were about implementing an unmarshaller interface (which I failed to figure what it is) and not unmarshalling standard duration.

**Comment by sethvargo** [comment]
Hi @dc0d 

I am unable to reproduce this.

```golang
package main

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/hashicorp/hcl"
)

type App struct {
	Exit time.Duration
}

const input string = `App { Exit = "5s" }`

func main() {
	var shadow interface{}
	if err := hcl.Decode(&shadow, input); err != nil {
		panic(err)
	}

	fmt.Printf("\n\n%#v\n\n", shadow)
	b, err := json.MarshalIndent(shadow, "", " ")
	if err != nil {
		panic(err)
	}
	fmt.Printf("\n\n%s\n\n", b)
}
```

This prints

```text
map[string]interface {}{"App":[]map[string]interface {}{map[string]interface {}{"Exit":"5s"}}}



{
 "App": [
  {
   "Exit": "5s"
  }
 ]
}
```

Do you have custom decoder hooks? Can you make sure you're using the latest version of the library?

**Comment by dc0d** [comment]
I have this commit:
```
commit ab403a54a148f2d857920810291539e1f817ee7b
Merge: 9240427 d379376
Author: Jesse Szwedko <jesse.szwedko@gmail.com>
Date:   Mon Apr 24 14:31:22 2017 -0700

    Merge pull request #616 from tbaud0n/master

    Fix autocomplete issue when multiple apps run autocomplete from etc/bash_completion.d directory
```
And `$ git status` gives:
```
On branch master
Your branch is behind 'origin/master' by 2 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
nothing to commit, working directory clean
```
As you see it says I'm behind HEAD by two commits. But even after doing `go get -u -v github.com/hashicorp/hcl`, I have the same `$ git log`.

What am I missing?

**Comment by sethvargo** [comment]
Hi @dc0d 

Can you share your actual code? You didn't share any of the code where you are actually parsing the HCL.

**Comment by dc0d** [comment]
This is the package (the part) that reads the config file:
```go
package tune

import (
	"fmt"
	"io/ioutil"
	"os"

	"github.com/hashicorp/hcl"
)

var (
	// DefaultConfNameHandler generates conf name,
	// conf file name: conf-<app_name>.conf or app.conf
	DefaultConfNameHandler = func() string {
		fp := fmt.Sprintf("conf-%s.conf", DefaultAppNameHandler())
		if _, err := os.Stat(fp); err != nil {
			fp = "app.conf"
		}
		return fp
	}
)

// LoadHCL loads hcl conf files;
// expected conf file name: DefaultConfNameHandler
func LoadHCL(ptr interface{}, filePath ...string) error {
	var fp string
	if len(filePath) > 0 {
		fp = filePath[0]
	}
	if fp == "" {
		fp = DefaultConfNameHandler()
	}
	cn, err := ioutil.ReadFile(fp)
	if err != nil {
		return err
	}
	err = hcl.Unmarshal(cn, ptr)
	if err != nil {
		return err
	}

	return nil
}
```

And in the app (`main` package) it gets called inside `init`:
```go
func init() {
	if err := tune.LoadHCL(&cnf); err != nil {
		switch err.(type) {
		case *os.PathError:
			log.Println("warn:", err)
		default:
			panic(err)
		}
	}
}
```

This is the conf struct:
```go
// CouchDBInfo .
type CouchDBInfo struct {
	URL      string
	User     string
	Password string
	DBName   string
}

// ConfPile all conf piled, dynamic values should not be placed inside conf
type ConfPile struct {
	Version string
	App     struct {
		LogDir       string
		PostponeExit time.Duration
		Env          string
		Version      string
	}

	// one object for each database
	PrimaryDB CouchDBInfo

	Start struct {
		Path     string
		Interval int
	}
}

var (
	cnf ConfPile
)
```

And the hcl file itself (named `app.conf`):

```
App {
    PostponeExit = 5000000000
    Env = "dev"
}

Vaqaye {
	URL      = "http://localhost:5984/"
	User     = "admin"
	Password = "admin_password"
	DBName   = "primarydb"
}
```

**Comment by sethvargo** [comment]
Smaller repro here:

```go
package main

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/hashicorp/hcl"
)

const input string = `
App {
  PostponeExit = "5s"
  Env = "dev"
}
`

type ConfPile struct {
	App struct {
		LogDir       string
		PostponeExit time.Duration
		Env          string
		Version      string
	}
}

func main() {
	var cnf ConfPile
	if err := hcl.Decode(&cnf, input); err != nil {
		panic(err)
	}

	b, err := json.MarshalIndent(cnf, "", " ")
	if err != nil {
		panic(err)
	}
	fmt.Printf("\n\n%s\n\n", b)
}
```

**Comment by dc0d** [comment]
Strange; running your code I get:
```
$ go build && ./gistcli 
panic: strconv.ParseInt: parsing "5s": invalid syntax

goroutine 1 [running]:
main.main()
	/.../my/gopath/src/draft/main.go:18 +0x94
```

**Comment by sethvargo** [comment]
Hi @dc0d 

Yea - I reproduced it. Sorry - I should have made that clearer. I was trying to get something down to the smallest possible repro.

Looking at the code, it looks like HCL doesn't handle time.Duration (you can grep the code for it). In most of our projects, we decode into an interface and then use [mapstructure](https://github.com/mitchellh/mapstructure) to map the values to the correct type.

**Comment by dc0d** [comment]
Thanks; seems adding it would require a bit of work (in tokenizer etc etc). It would help & make things more clear if it gets mentioned in the docs.

**Comment by sethvargo** [comment]
Yea, I'm going to defer to @jbardin or @mitchellh on whether it should be in HCL core or not.

**Comment by dc0d** [comment]
@sethvargo Thanks for your time! IMHO it's not that rare to use a duration in settings.

**Comment by jefferai** [comment]
Note that parsing time.Duration directly is likely not what you want, because it's an int64 containing nanoseconds which is usually not what's expected. There is some code in Vault that takes in the value from the hcl as an interface in e.g. DurRaw, then parses using a helper into a Dur value that accepts either a string or integer number of seconds. It works for Vault, but the problem with doing this dogmatically in the library is that if someone did actually want to encode a number of nanoseconds, it would be impossible. At a library level I'm not sure that's a good idea.

**Comment by dc0d** [comment]
Seems logical and I can't judge the frequency of using nanoseconds/milliseconds/seconds/...; so this should get closed. Thanks for follow up!
