### ISSUE TITLE
README example is broken

### ISSUE THREAD

**Issue by philshafer** [hashicorp/hcl#205]
The example in the README.md is missing a set of brackets:

```
{
  "variable": {
      "ami": {
          "description": "the AMI to use"
        }
    }
}
```

should be:

```
{
  "variable": [
     {
      "ami": {
          "description": "the AMI to use"
        }
     }
   ]
}
```

This matches the content on https://www.terraform.io/docs/configuration/syntax.html

Thanks,
 Phil

**Comment by bridgetlane** [comment]
The example in the README is valid based on the page you linked, the example under JSON Syntax matches the one without brackets.

**Comment by philshafer** [comment]
Ah, okay.  I was thinking the "variable = [...]" meant that this was an array, but the text clearly says it's still a map.  Apologies for the confusion.

Thanks,
 Phil
