### ISSUE TITLE
Allow me to customize the value of SpacesWidth

### ISSUE THREAD

**Issue by mrwacky42** [hashicorp/hcl#212]
### Expected behavior
I would like to allow `terraform fmt` to let me specify SpacesWidth, because I am curmudgeon who wants something different than 2 space indentation.
However,  `fmtcmd` and `printer` do not allow me to customise the config.

### Actual behavior

* Terraform calls [fmtcmd.Run](https://github.com/hashicorp/terraform/blob/master/command/fmt.go#L79)
* This calls [fmtcmd.Processfile](https://github.com/hashicorp/hcl/blob/master/hcl/fmtcmd/fmtcmd.go#L113)
* Which calls [printer.Format](https://github.com/hashicorp/hcl/blob/master/hcl/fmtcmd/fmtcmd.go#L67)
* Which calls [DefaultConfig.Fprint](https://github.com/hashicorp/hcl/blob/master/hcl/printer/printer.go#L59)

It would be nice if there was a way to use a different config than the default.

**Comment by sethvargo** [comment]
Hi @mrwacky42 

Thank you for opening an issue. The HCL specification is two spaces, so that's what the formatter is going to do. You can disable auto-formatting in your editor (or not run the command), but the point of the `terraform fmt` and similar commands is to provide a consistent experience. Thanks and have a great day! 😄

**Comment by mrwacky42** [comment]
Hi @sethvargo,
A thousand (tiny) curses upon Hashicorp for calling a struct `Config` when it is not, in fact, configurable.
Fortunately, I think the many blessings of Terraform cancel out these curses. 

But seriously, why does HCL uses spaces yet the rest of the Golangiverse uses tabs?
And why doesn't the HCL specification (presumably the [README.md](https://github.com/hashicorp/hcl/blob/master/README.md) state two spaces as the standard?
