### ISSUE TITLE
Nothing on STDOUT when terraform fmt -write=false

### ISSUE THREAD

**Issue by andersla** [hashicorp/hcl#217]
### HCL Template
```hcl

# this is my test vars in the terraform.tfvars
cluster_prefix = "anderskubenow"
location = "West Europe" 

```

### Expected behavior
The formatted file should be printed on STDOUT 
according to:
https://www.terraform.io/docs/commands/fmt.html

### Actual behavior
Nothting is printed on STDOUT

### Steps to reproduce
1. terraform fmt --write=false terraform.tfvars

Terraform v0.10.7
Ubuntu 16.06

### References
Are there any other GitHub issues (open or closed) that should
be linked here? For example:
- GH-1234
- ...

**Comment by sethvargo** [comment]
Hi @andersla 

This is the generic HCL parsing and printing library. Could you please open an issue with Terraform? This is a much lower-level API, and the bug is likely in Terraform itself. Thanks!

**Comment by andersla** [comment]
Closed and opened issue with Terraform instead:-)
https://github.com/hashicorp/terraform/issues/16308
