### ISSUE TITLE
Allow passing heredoc to function

### ISSUE THREAD

**Issue by tmshn** [hashicorp/hcl#238]
I want to pass heredoc to interpolate functions.

### HCL Template

```hcl
resource "google_logging_project_sink" "awesome_sink" {
  name        = "..."
  destination = "..."

  filter = "${chomp(<<EOT
resource.type="gke_cluster"
AND resource.labels.cluster_name="my-awsome-cluster"
EOT
)}"
  # or
  filter = "${chomp(<<EOT)}"
resource.type="gke_cluster"
AND resource.labels.cluster_name="my-awsome-cluster"
EOT

}
```

### Expected behavior
What should have happened?

Parse correctly and `filter` will be `"resource.type=\"gke_cluster\"\nAND resource.labels.cluster_name=\"my-awsome-cluster\'"`

### Actual behavior
What actually happened?

Parse Error

**Comment by octo** [comment]
String interpolation is not done in HCL but [HIL](https://github.com/hashicorp/hil), therefore this feature request should be filed against HIL instead.

That said, I find the first proposed option hard to read and think that the second option breaks the strict and intuitive distinction between HCL and HIL.

For the use-case you've given, I'd recommend doing the following:

```
filter = <<-EOF
    resource.type="gke_cluster"
    AND resource.labels.cluster_name="my-awsome-cluster"
    EOF
```

This is a heredoc that trims the indentation of the delimiter from all preceding lines.

Best regards,
—octo

**Comment by tmshn** [comment]
Oh, I didn't know the HIL...I'd been thinking everything is done in HCL. That's good to know.

Actually, I fixed my problem in the following pull request, so I'll close this.

https://github.com/terraform-providers/terraform-provider-google/pull/1206

Thanks anyway!
