### ISSUE TITLE
Make commas in lists optional

### ISSUE THREAD

**Issue by nikolay** [hashicorp/hcl#27]
I don't see why there's need for commas. Make them optional for backward-compatibility.

**Comment by mitchellh** [comment]
What do you mean for backwards compatibility? Did we introduce a backwards incompatible change somewhere since HCL was made? Can you show an example?

**Comment by nikolay** [comment]
I mean, if people have old style configs with comma-delimited lists, making commas optional will still work for the old.

What I'm proposing is this:
* Old style: `[10, 20, 30]`, `["a", "b", "c"]`
* New style: `[10 20 30]`, `["a" "b" "c"]`

**Comment by mitchellh** [comment]
We've never had non-comma delimited lists, so I'm still confused what you're talking about, sorry. Even if we did, that was never intended. I'm not going to support that.

**Comment by nikolay** [comment]
Sorry if I was too confusing. I never meant that you did support that. I proposed that you make commas in lists optional. Those who find configurations more readable with commas can still use them. And the others won't be forced to use them.

**Comment by mitchellh** [comment]
Ah, I don't see any real use case for that other than style and a style I don't really agree with. Why make it more confusing? One syntax to do one thing is better than ambiguity.
