### ISSUE TITLE
Comment standard for HCL JSON

### ISSUE THREAD

**Issue by eropple** [hashicorp/hcl#28]
Hey there--

So as part of building [Terraframe][tf] I'm finding myself needing to occasionally need to inject a human-readable comment into the JSON output (largely for debugging). Having to strip my comments back out before feeding it into Terraform is a drag.

Maybe we could standardize on, say, any field beginning with "//" being ignored by the HCL reader? Example:

```json
{
  "//builder": "Built by Terraframe 0.1.0.",
  "resource": {
    "aws_instance": {
      "test": {
        "//source": "test_instance.terraframe:25",
      }
    }
  }
}
```

It'd help with building good tooling on top of the platform, and would make my life a lot easier. :)

Thanks!

[tf]: http://github.com/eropple/terraframe

**Comment by mitchellh** [comment]
We're trying not to divert from the JSON spec in any big way. The only place we do right now is allowing trailing commas on lists/objects. But I don't think I'd want to introduce this. The idea with HCL's JSON support is that a machine generates it directly and it is meant to be a machine-to-machine interface. If you need comments, that means a human might read it, which is what HCL was made for (human to machine).

The only other thing I _might_ be open to is just introducing comments outright, but again, I'd really like to avoid this. 

Use HCL for human to machine
JSON for machine to machine
