### ISSUE TITLE
Expressions and Functions. 

### ISSUE THREAD

**Issue by timothysc** [hashicorp/hcl#30]
I'm very curious if you plan to enable expression and functions and to what extent you plan to build out the configuration language.

**Comment by timothysc** [comment]
1 month and no comment?  I was hoping to leverage this.

**Comment by mitchellh** [comment]
We've built a full expression/function system into Terraform outside of HCL that we'll likely extract as a separate package. The two will be able to be used together to get what you want.

**Comment by virtuald** [comment]
I'd rather keep expressions/functions outside of HCL and leave anything like that up to the application that uses it.

**Comment by mitchellh** [comment]
@virtuald Right, we plan on making it a separate Go package.

**Comment by mytototo** [comment]
Any news about functions in HCL files? I'm very much interested.
