### ISSUE TITLE
Interoperability with HOCON

### ISSUE THREAD

**Issue by benmccann** [hashicorp/hcl#31]
hcl sounds almost exactly the same as [HOCON](https://github.com/typesafehub/config/blob/master/HOCON.md), which I've contributed to in the past. They both have very JSON-like file formats and there's quite a bit of overlap. They both support types like `1kb` even! It'd be cool if maybe the two could work together to define a common spec.

Right now HOCON is used by a lot of Scala & Java projects since Typesafe authored the original client. Puppet has also created a [Ruby version](https://github.com/puppetlabs/ruby-hocon/blob/master/README.md) that they're using.

Hocon supports some features that hcl doesn't such as importing files and having types for durations, which I think could be added to hcl fairly easily I think. I'm not super fluent in yacc, but it looks like hocon and hcl may handle variables slightly differently, so it's pretty similar as both support syntax like `${aws_instance.web.id}`. The [Terraform docs](http://www.terraform.io/docs/configuration/interpolation.html) seem to have more details on this than the hcl README, so that might be a good place to look.

Not sure if this is worth the effort, but thought it was worth making you guys aware of each other's projects in case there is anything that does make sense.

CC @havocp - maintainer of hocon

**Comment by benmccann** [comment]
CC @timothysc who may also be interested in this

**Comment by havocp** [comment]
For what it's worth there's also HJSON http://hjson.org/ and Jsonnet https://github.com/google/jsonnet out there.

**Comment by mitchellh** [comment]
These look great! However we don't have the bandwidth right now to focus on these sorts of efforts with relation to HCL. However its a great idea for "one day". Sorry!

**Comment by timothysc** [comment]
@benmccann, @havocp many thanks! that's pretty much what I've been looking for.

**Comment by cricket007** [comment]
Sorry for digging this up, but with the efforts on HCL2, I will say that HOCON has [lots more transparent example documentation](https://github.com/lightbend/config/blob/master/HOCON.md#syntax). 

Don't get me wrong, all for things written in Go rather than Java, but looks like [go-akka](https://github.com/go-akka/configuration) has that covered. 

AFAICT, there is a very slim difference between HOCON and the HCL I've written thus far...
