### ISSUE TITLE
Support of line breaking for long lines

### ISSUE THREAD

**Issue by richardzone** [hashicorp/hcl#312]
```hcl
  network_rules {
    default_action = length(var.allowed_subnet_ids) == 0 && length(var.allowed_public_ip_ranges) == 0 ? "Allow" : "Deny"
    bypass         = "AzureServices"
  }
```

The above template works. However, it is quite long and requires horizontal scroll if editor does not enable line wrap.

It would be nice to be able to break this down into multiple lines, like this:
### Suggested way

```hcl
  network_rules {
    default_action =
      length(var.allowed_subnet_ids) == 0 &&
      length(var.allowed_public_ip_ranges) == 0 ? "Allow" : "Deny"
    bypass         = "AzureServices"
  }
```

But currently the parser will issue error for this.

**Comment by apparentlymart** [comment]
Hi @richardzone!

Similar to Python (which is also whitespace-sensitive in its syntax), HCL allows wrapping expressions over multiple lines if you place the multi-line portion in some form of brackets to help the parser understand your intent. In your case, you could achieve this with parentheses:

```hcl
    default_action = (
      length(var.allowed_subnet_ids) == 0 &&
      length(var.allowed_public_ip_ranges) == 0 ? "Allow" : "Deny"
    )
```

This also works for brackets `[` `]` and braces `{` `}` when writing tuple and object constructor syntax, or `for` expressions:

```hcl
  example1 = [
    "foo",
    "bar",
    "baz",
  ]
  example2 = {
    foo = "bar"
    baz = "boop"
  }
  example3 = [
    for x in y : {
      name = x.name
    }
  ]
```

...and the parentheses for a function call also function in a similar way as the grouping parentheses:

```hcl
  example4 = function(
    foo,
    bar,
    baz,
  )
```

The general rule here is that newline is interpreted as a significant token only when the number of open bracket pairs is zero. If there's at least one bracket pair open, a newline is treated the same as any other whitespace and ignored altogether.
