### ISSUE TITLE
How to read nested keys in hcl

### ISSUE THREAD

**Issue by youshy** [hashicorp/hcl#324]
```hcl
resource "file" "new_file" {
  path = "/tmp/new-file.txt"
  chmod = 644
  owner = "root"
  group = "root"
  content = "Hello"
}
```

Reader
```golang

type Resource struct {
	Resource []Service `hcl:"resource,label"`
}

type Service struct {
	Name    string `hcl:",key"`
	Sname   string `hcl:",attribute"`
	Path    string `hcl:"path"`
	Chmod   int    `hcl:"chmod"`
	Owner   string `hcl:"owner"`
	Group   string `hcl:"group"`
	Content string `hcl:"content"`
}
```

How to read/unmarshal the second key from the hcl file? Rest of the keys are easily readable, but I can't get `Sname` to work (yes, I know, it's not the best name ever...). I've tried multiple options with none working properly.

### References
- #214 // asked two years ago

**Comment by apparentlymart** [comment]
Hi @youshy!

Are you using HCL v1 or HCL v2 here?

I don't know the answer for HCL 1, but for HCL 2's [`gohcl`](https://pkg.go.dev/github.com/hashicorp/hcl/v2/gohcl?tab=doc) I think a struct annotated like this should do it:

```hcl
type Resource struct {
	Resource []Service `hcl:"resource,block"`
}

type Service struct {
	Name    string `hcl:"name,label"`
	Sname   string `hcl:"sname,label"`
	Path    string `hcl:"path"`
	Chmod   int    `hcl:"chmod"`
	Owner   string `hcl:"owner"`
	Group   string `hcl:"group"`
	Content string `hcl:"content"`
}
```

Note that your `chmod` attribute here will be interpreted by HCL as decimal digits, not octal digits as I expect you were hoping. I'd recommend marking that one as a string too and having the user set it like `chmod = "644"` to make the octal base more explicit and reduce the chance of confusing misbehavior by using decimal by mistake.

**Comment by youshy** [comment]
@apparentlymart works like a charm! Thank you!
