### ISSUE TITLE
Difference between documentation and grammar about lists (arrays)

### ISSUE THREAD

**Issue by VladRassokhin** [hashicorp/hcl#33]
As `README.md` says:
> Arrays can be made by wrapping it in []. Example: ["foo", "bar", 42]. Arrays can contain primitives and other arrays, but cannot contain objects. Objects must use the block syntax shown below.

At the same time in [`hcl/parse.y`](https://github.com/hashicorp/hcl/blob/master/hcl/parse.y#L174:L185)
```bnf
listitem ::= number | STRING
```
Note `list` is missing here.

Please update either documentation or grammar

Also note there's difference in naming: array vs list

**Comment by fatih** [comment]
I can confirm this too, the following gives an error, because it doesn't allow to contain an array:

```
package main

import (
	"fmt"

	"github.com/hashicorp/hcl"
)

func main() {
	ex := `a = ["fatih", 123, ["a", 45]]`
	if _, err := hcl.Parse(ex); err != nil {
		fmt.Println("ERROR", err)
	}
}
```

**Comment by let4be** [comment]
How one define an array of objects?... I'm having a hard time figuring it out

**Comment by julien** [comment]
@let4be from what I saw in the examples, it should be like this:

```
foo "bar" {
  value = "stuff"
}
foo "baz" {
  value = "more stuff"
}
```

What I'm having trouble with is nesting, i.e.

```
foo {
   stuff = "thing"
   bar {
     value = "more here"
   }
}
```

Doesn't seem to be the right way

**Comment by mitchellh** [comment]
The README is wrong at the moment, we don't currently support nested lists. We may reapproach this in the future but at the moment we're not doing this. Updating the README now.
