### ISSUE TITLE
Multi-line string

### ISSUE THREAD

**Issue by arr-dev** [hashicorp/hcl#34]
I have a rather long command as a string in hcl.
```
provisioner "local-exec" {
  command = "knife solo bootstrap -N ${self.name} -j '{\"mysql\": {\"server_root_password\": \"${var.mysql_root_password}\"}}' --no-berkshelf --no-host-key-verify -i ${var.pvt_key} -r ${var.run_list.db} ${var.remote_user}@${self.ipv4_address} | tee -a ${self.name}.log
}
```

Is there a way to break it and still keep it decoded as a single string?
I can't find anything in test fixtures regarding this.

**Comment by VladRassokhin** [comment]
Not sure about multiline strings, but it's better `local-exec` provisioner to accept array of strings (each argument as separate list item):
```text
  command = ["knife", "solo", "bootstrap", "-N", etc]
```

Or allow `+` as strings concatenation rather than multiline strings.

**Comment by arr-dev** [comment]
Yes, either way would be good, but I don't think it accepts any of that?

**Comment by VladRassokhin** [comment]
AFAIK, no. `local-exec` [expects string](https://github.com/hashicorp/terraform/blob/master/builtin/provisioners/local-exec/resource_provisioner.go#L34) and hcl does not support operators, see [grammar](https://github.com/hashicorp/hcl/blob/master/hcl/parse.y)

**Comment by wallyqs** [comment]
+1

**Comment by VladRassokhin** [comment]
Actually hcl supports heredoc syntax:
```hcl
a = <<EOF
Text
Here
EOF
```
So issue could be closed. // cc @mitchellh

**Comment by mitchellh** [comment]
Agreed

**Comment by fosskers** [comment]
Unfortunately HEREDOC syntax breaks Emacs' `terraform-mode`, so I've opted to use a giant one-liner and sacrifice readability.

**Comment by mitchellh** [comment]
That works until that's fixed :) Not sure who maintains the terraform-mode!

**Comment by fosskers** [comment]
https://github.com/syohex/emacs-terraform-mode/issues/14

**Comment by ndoshi-mz** [comment]
`command =<<EOF.`
make sure there is no characters after EOF even a space character will throw off heredoc and it will fail.

**Comment by fosskers** [comment]
Hi me from the past. I tested it again just now, and it works fine.

**Comment by ypz** [comment]
This syntax worked for me with Terraform version 0.12.x:

```
resource "null_resource" "test" {
  provisioner "local-exec" {
     command = join(" ", ["some-cmd", 
                          "arg1", 
                          "arg2"])
  }
}
```
