### ISSUE TITLE
Error Message for Bitwise OR  references boolean AND "&&" 

### ISSUE THREAD

**Issue by martinei** [hashicorp/hcl#376]
### HCL Template

```hcl
foo = a | b
```

### Expected behavior
Get an error Message:

>Bitwise operators are not supported. Did you mean boolean OR ("||")?

### Actual behavior
Got an error message

> Bitwise operators are not supported. Did you mean boolean OR ("&&")?

### Steps to reproduce
Stumbled upon this one in terraform.
Have a look at https://github.com/hashicorp/hcl/blob/hcl2/hclsyntax/token.go#L205

**Comment by alisdair** [comment]
Fixed in #380
