### ISSUE TITLE
Continuous fuzzing

### ISSUE THREAD

**Issue by AdamKorcz** [hashicorp/hcl#379]
With fuzzing being a priority of the hcl language and @alisdair writing a lot of good fuzzers, would it be of interest to see if we can get hcl accepted into oss-fuzz?

I can confirm that the fuzzers can run on their infrastructure, and I will be glad to setup an integration application.

oss-fuzz is offered free of charge, however, there is an expectation that the bugs are fixed, so that the fuzzers can go on and find other bugs.

If a bug is found, all maintainers on the projects contact list are notified with a detailed bug report.

To integrate hcl into oss-fuzz, all I need are the email addresses for the bug reports. These need to be added to a public list that can be changed at any time.

**Comment by x509cert** [comment]
I am not on the hcl team, but this seems reasonable to me. I think the expectation of fixing issues is reasonable, too..

**Comment by alisdair** [comment]
Thanks for the offer, but we're already running the hcl fuzz tests continuously on a Nomad cluster with some internal tools.

**Comment by phretor** [comment]
@alisdair I created an integration of hclsyntax's fuzzers into OSS-Fuzz: https://github.com/google/oss-fuzz/pull/5924/commits/46e9bd843232ea638894bef772bbeef0ff6b1524
