### ISSUE TITLE
IS there support for anything similar to YAML's anchor/alias concept?

### ISSUE THREAD

**Issue by blade2005** [hashicorp/hcl#394]
Not a issue per se but more feature request.

I'm passing a multiple arguments to a module in terraform and thought I'm repeating myself a lot here for this, would this be much easier if I just pass an alias from an anchor.

Does this exist in HCL at present? If not has it been considered?

**Comment by apparentlymart** [comment]
Hi @blade2005,

For HCL, that sort of thing is for the application to provide at its own level of abstraction, not something innate in the underlying grammar. Terraform in particular has its own features for factoring out certain constructs, while in some cases it intentionally doesn't allow that out of a preference for keeping configurations relatively flat and straightforward.

With that said, if you'd like to talk more about the situation(s) you've found in Terraform where you'd like a way to write something once and use it many times, the Terraform team would like to hear about it in the Terraform repository!
