### ISSUE TITLE
How to inline yaml for the "content_value"'s 'url' field of azurerm_api_management_api

### ISSUE THREAD

**Issue by tezzigator** [hashicorp/hcl#400]
I was referred by the azurerm provider group to open a HCL issue for [this problem I have](https://github.com/terraform-providers/terraform-provider-azurerm/issues/8306).

### HCL Template
```
resource "azurerm_api_management_api" "get" {
  name                = "apimpetstoreget"
  resource_group_name = data.azurerm_resource_group.rg.name
  api_management_name = azurerm_api_management.apim.name
  revision            = "1"
  display_name        = "'PetstoreGet"
  path                = "apimpetstore"
  protocols           = ["https"]

  import {
    content_format = "openapi"
    content_value  = <<-EOT
    openapi: 3.0.1
    info:
      title: Get Store
      version: '1.0'
    servers:
      - url: 'http://${azurerm_container_group.container.ip_address}:8080/v2'
    paths:
      /store/inventory:
        get:
          summary: Retrieve resource
          description: >-
            A demonstration of a GET call on a sample resource. It is handled by an
          responses:
            '200':
              description: Returned in all cases.
    components:
      securitySchemes:
        apiKeyHeader:
          type: apiKey
          name: Ocp-Apim-Subscription-Key
          in: header
        apiKeyQuery:
          type: apiKey
          name: subscription-key
          in: query
    security:
      - apiKeyHeader: []
      - apiKeyQuery: []
    EOT
  }
}
```

### Expected behavior
Expected the inline yaml config to completely deploy

### Actual behavior
YAML was nearly 100% deployed, except 1 field: the interpolation of
```
url: 'http://${azurerm_container_group.container.ip_address}:8080/v2'
```
as the "HTTP(s) endpoint" never makes it into the Azure APIM system. When terraform spits out its plan, it does interpolate correctly, to
```
url: 'http://10.0.2.4:8080/v2'
```
 but that just never gets set to Azure - I have to then go in manually in the Azure Portal to set that URL and then everything is fine.

### References
[Original terraform-provider-azurerm issue 8306](https://github.com/terraform-providers/terraform-provider-azurerm/issues/8306) where they asked I bring this to HCL

**Comment by apparentlymart** [comment]
Hi @tezzigator,

I'm not sure what you mean by "it never gets set to Azure" here, but either way this seems to be a Terraform question rather than an HCL issue and so I'm afraid I'm going to have to re-refer you to [the Terraform community forum](https://discuss.hashicorp.com/c/terraform-core). This repository is for the development of the grammar underlying Terraform, but the behavior you're describing belongs to Terraform and the Azure provider and so we can't help with it here.
