### ISSUE TITLE
Definition of a NUMBER and FLOAT

### ISSUE THREAD

**Issue by fatih** [hashicorp/hcl#41]
Hi. This is not an issue, just some questions around the HCL spec. According to the README:

```
Numbers are assumed to be base 10. If you prefix a number with 0x, it is treated as a hexadecimal. If it is prefixed with 0, it is treated as an octal. Numbers can be in scientific notation: "1e10".
```

I have couple of questions about this (where NUMBER and FLOAT are HCL tokens).

* Can we assume that NUMBER in HCL do have the same set of spec as integer literals in Go: https://golang.org/ref/spec#Integer_literals ?
* Can we assume that a FLOAT token is also the same as a Go float: https://golang.org/ref/spec#Floating-point_literals ?
* Shouldn't be `1e10` a FLOAT? The description above makes it like it's a NUMBER.

**Comment by mitchellh** [comment]
I'd be happy to clarify the spec further or even modify HCL if the following doesn't make sense, but the following is how HCL works now:

* For any of the above, if there is no `.` found, it is a NUMBER (and therefore int)
* If a `.` is found, it is a FLOAT.

Real examples:

* `1` `07` `0x42` `1e4` are all ints, NUMBER
* `1.8e4` `0.1` are FLOAT

**Comment by fatih** [comment]
Thanks @mitchellh 

So this means, as a difference  literals in form of `1e4` are a NUMBER, whereas in Go they are treated as FLOAT. I think this is the only difference right now.
