### ISSUE TITLE
README: Is this repo HCL1 or HCL2?

### ISSUE THREAD

**Issue by bshanks** [hashicorp/hcl#439]
The README says "NOTE: This is major version 1 of HCL, which is now in maintenence mode only. We strongly recommend that new projects use HCL 2 instead.". However I cannot find a link to HCL 2. Furthermore https://github.com/hashicorp/hcl2 links back to this repo, saying "This repository was used for the initial development of version 2 of HCL, but is now archived because the work from this repository was incorporated back in to the main HCL repository.".

If this repo does in fact contain HCL 2, then I suggest removing the NOTE. If it does not, then I suggest linking to HCL 2 in the NOTE

### References
None

**Comment by bshanks** [comment]
Also the README in https://github.com/hashicorp/hcl2 seems to contain more/different information than the README in this repo, yet the README in https://github.com/hashicorp/hcl2 refers back to here. I suggest adding the information from the https://github.com/hashicorp/hcl2 README to here.

**Comment by pselle** [comment]
@bshanks The repo's default branch is HCL1, which prevents breaking users who might not be using Go modules when using HCL [1]. The README you're looking for can be found at https://github.com/hashicorp/hcl/tree/hcl2. It most definitely could be clearer.

**Comment by pselle** [comment]
Hey there, the default branch of this repo is now HCL2! I hope this resolves some confusion here.
