### ISSUE TITLE
cannot find package "github.com/hashicorp/hcl/hcl/printer"

### ISSUE THREAD

**Issue by luffy51k** [hashicorp/hcl#454]
hi, im build go project, got error:

package github.com/hashicorp/hcl/hcl/printer: cannot find package "github.com/hashicorp/hcl/hcl/printer" in any of:
        /usr/local/go/src/github.com/hashicorp/hcl/hcl/printer (from $GOROOT)

howto fix it?

**Comment by apparentlymart** [comment]
Hi @luffy51k! Sorry for the late response.

You can find an earlier answer to this question in #449. Thanks!
