### ISSUE TITLE
Is timestamp function not supported in HCL2?

### ISSUE THREAD

**Issue by kais19** [hashicorp/hcl#457]
I am trying to get the current day and put in a local 
```
locals {
  current_day = formatdate("DD/MM/YYYY", timestamp())
}
```
but a I get this error ``` Call to unknown function; There is no function named "timestamp".```
Is timestamp function not supported in HCL2 anymore?
If so, is there any other way to get the current day?

**Comment by apparentlymart** [comment]
Hi @kais19,

This seems like a Terraform question rather than an HCL issue. A better place to ask questions about Terraform is in [Terraform's community forum](https://discuss.hashicorp.com/c/terraform-core). Thanks!
