### ISSUE TITLE
Did expand tag go away?

### ISSUE THREAD

**Issue by ChrisMcKenzie** [hashicorp/hcl#46]
Just updated to the latest hcl code and will no longer expand hcl object into slice of structs

```
var deploy struct {
	Services []service.Config `hcl:"service,expand"`
}
```

This used to work.

**Comment by mitchellh** [comment]
Thanks! I'll get a test case in here to fix this right away. What is an example input to help as well?

**Comment by ChrisMcKenzie** [comment]
A simplified version of my input is this:

```
service "my-service-0" {
  key= "value"
}

service "my-service-1" {
  key= "value"
}
```

**Comment by mitchellh** [comment]
Hey @ChrisMcKenzie I added a unit test in HCL for this. Take a look at the test, it decodes just fine. Is there something you're doing differently during decode?

**Comment by ChrisMcKenzie** [comment]
I was actually just about to post I saw the `structuredarray` was passing I am looking in to what I am doing differently right now.

**Comment by mitchellh** [comment]
Thanks please let me know, would love to fix this up. There were changes with `expand` (it was removed) but that is only because it became unnecessary: we do the right thing without it now.

**Comment by ChrisMcKenzie** [comment]
Ok so it turned out to not be related to the top level of my struct but actually a struct inside.
It appears that when `hcl:",key"` is set on a field whose type is a struct I get an "key impossible" error.
I am assuming this is proper behavior?

I would have found this long before if I would have logged the error. :facepalm:

here is the full version of my "working" structs 
```
type Artifact struct {
	Type        string `hcl:",key"`
	Bucket      string `hcl:"bucket"`
	Path        string `hcl:"path"`
	Destination string `hcl:"destination"`
}

type Hook struct {
	Type   string `hcl:",key"`
	Config string `hcl:"config"`
}

type Config struct {
	Name          string     `hcl:",key"`
	CheckInterval string     `hcl:"checkInterval"`
	BeforeHooks   []Hook     `hcl:"before,expand"`
	AfterHooks    []Hook     `hcl:"after,expand"`
	Sequential    bool       `hcl:"sequentialUpdates"`
	Artifact      []Artifact `hcl:"artifact"`
}

type ServiceFile struct {
	Services []Config `hcl:"service,expand"`
}
```
