### ISSUE TITLE
Heredoc support removed in new HCL parser

### ISSUE THREAD

**Issue by rgabo** [hashicorp/hcl#47]
Heredoc support seems to be gone with #45, `hcl/scanner/scanner.go` does not tokenize `<` like the old lexer did: https://github.com/hashicorp/hcl/commit/26239b8eab901433e15c3c6d27e1f8065b0fbe83#diff-3ea40c09007c8c8608ccf619755a4adfR97

Created issue to track @jen20's work on https://github.com/hashicorp/hcl/tree/b-heredoc-decoding

@jen20 https://github.com/hashicorp/terraform/issues/3840 just bit me on `master` in a dev build, I thought an open issue would be nice in `hcl` to see what's going on.

**Comment by mitchellh** [comment]
Uh oh! I'm going to add this ASAP today. I completely forgot about this.

**Comment by rgabo** [comment]
Thanks @mitchellh for jumping on this quickly. Great work with the new parser. Glad we bumped into the issue quickly and tests were added.

**Comment by rgabo** [comment]
@mitchellh if you haven't started yet, I ended up implementing this myself in #48. I wanted to contribute back in Go for some time and this seemed like a fun one :smile:
