### ISSUE TITLE
String escape rules changed with new HCL parser

### ISSUE THREAD

**Issue by rgabo** [hashicorp/hcl#50]
Probably best solved with documentation or better error messages, but the rules to escape quotes inside a quoted string literal has changed in the new HCL parser:

Old parser:

```
resource "template_file" "kafka" {
  filename = "/dev/null"
  vars {
    broker_list = "${join(\",\", formatlist(\"%s:%d\", aws_route53_record.kafka.*.name, 9092))}"
    zookeeper_list = "${join(\",\", formatlist(\"%s:%d\", aws_route53_record.kafka.*.name, 2181))}"
  }
}
```

New parser:

```
resource "template_file" "kafka" {
  filename = "/dev/null"
  vars {
    broker_list = "${join(",", formatlist("%s:%d", aws_route53_record.kafka.*.name, 9092))}"
    zookeeper_list = "${join(",", formatlist("%s:%d", aws_route53_record.kafka.*.name, 2181))}"
  }
}
```

Relevant code in HCL scanner: https://github.com/hashicorp/hcl/blob/master/hcl/scanner/scanner.go#L455

This could be an issue with unsuspecting Terraform users upgrading to 0.6.7 and suddenly seeing syntax errors.

As a side-effect, the change also brakes syntax highlighting in [Sublime Text](https://www.dropbox.com/s/n862magjg238omr/Screenshot%202015-11-11%2016.44.34.png?dl=0) but not in [vim](https://www.dropbox.com/s/vvsyhqw695ul6vh/Screenshot%202015-11-11%2016.45.04.png?dl=0).

The new syntax is easier to write and read, but it is a breaking change so I wanted to make sure it was addressed before downstream releases.

**Comment by mitchellh** [comment]
Hm this is interesting, the old parser also ignored any escapes. I think the lsat version also just allowed them as well as ignoring them, which is rather confusing. You can see the old lexer here: https://github.com/hashicorp/hcl/blob/e37b5bd61b651c9fbf4548fc41b83e4f3d91dad0/hcl/lex.go#L358

The reason I did this was actually a failed test from the old parser! We had tests to make sure what you have marked as "new parser" actually worked in the old one as well. I think the difference is that both the old and new version you have above worked. 

I'll take a look at making this work.

**Comment by mitchellh** [comment]
I took a look and our Terraform docs never mentioned being able to escape. I think this was an unintended feature of our last parser. Going to close this. We'll document this change in the Terraform release notes.

![2015-11-11_at_10 36_am](https://cloud.githubusercontent.com/assets/1299/11099453/4c3194d2-8860-11e5-8142-dd619b5fd36c.png)

**Comment by rgabo** [comment]
I'm not entirely sure where the escaping came from, I'll see if I can
figure out. Thanks for looking into it.
