### ISSUE TITLE
Unified error logging w/ token position

### ISSUE THREAD

**Issue by chiefy** [hashicorp/hcl#54]
Currently the scanner will output errors including token position (line/col) format which is great for creating linters for text editors. I am trying to create a linter for Sublime Text, but noticed that some of the errors [don't reference token position in the parser](https://github.com/hashicorp/hcl/blob/master/hcl/parser/parser.go#L176).

**Comment by mitchellh** [comment]
Agreed. I'll start sweeping these up but please continue to point out any places you don't find the location.

**Comment by chiefy** [comment]
thanks @mitchellh :+1:
