### ISSUE TITLE
Decoding arbitrary map[string]string with gohcl

### ISSUE THREAD

**Issue by everdrone** [hashicorp/hcl#547]
I've been looking for a solution in other issues like: https://github.com/hashicorp/hcl/issues/536 but so far I couldn't manage to find one fitting my case.

I'm trying to decode the following block using `gohcl`:
```hcl
headers {
  Content-Type = "application/json"
  Charset = "utf-8"
  ArbitraryKey = "some string"
}
```
Into a `map[string]string`, like:

```go
type Config struct {
    Headers map[string]string `hcl:"header,block"`
}
```

The problem is the keys are arbitrary and I can't find a straightforward way of doing this.
Still can't wrap my head around `hcl.Attributes`, `hcl.Body` and `hcl.Expression`

**Comment by everdrone** [comment]
Turns out that it's enough to change the `headers` block into an attribute:

```hcl
headers = {
  Content-Type = "application/json"
  Charset = "utf-8"
  ArbitraryKey = "some string"
}
```

```go
type Config struct {
    Headers map[string]string `hcl:"header"`
}
```

**Comment by ShradhaKhard** [comment]
I am struggling to parse a complex type too. 

https://www.hashicorp.com/blog/default-tags-in-the-terraform-aws-provider

```
default_tags {
   tags = {
     Environment = "Test"
     Owner       = "TFProviders"
     Project     = "Test"
   }
 }
```

Trying to read all the key/value pairs for the `tags` attribute. I am using `github.com/hashicorp/hcl/v2/hclwrite` package to convert the `.tf` file to `HclFile *hclwrite.File`.  


```
        file, diags := hclwrite.ParseConfig(buf, fileName, hcl.Pos{Line: 1, Column: 1})
	if diags.HasErrors() {
		fmt.Printf("errors: %s", diags)
		return TerraformBlob{}, fmt.Errorf(diags.Error())
	}

         for _, block := range file.Body().Blocks() {

		if block.Type() == "provider" && block.Labels()[0] == "aws" {
			// if default_tags block already exists, update the tags
			defaultTagsExists := false
			for _, nestedBlock := range block.Body().Blocks() {
				if nestedBlock.Type() == "default_tags" {
					defaultTagsExists = true
					tagsAttr := nestedBlock.Body().Attributes()["tags"]
					fmt.Printf("got it: %#v\n", tagsAttr) **// here I can print the attr object but can't figure how to read the 
 existing tags**
					
				}

			}
			if defaultTagsExists {
				// merge tags with new key/value or update the value for existing keys
				continue //outer for loop
			}

			// add default_tags block to provider block, if not present
			defaultTags := block.Body().AppendNewBlock("default_tags", nil)
			defaultTags.Body().SetAttributeValue("tags", populateObjectVal(data))

		}
	}
```

In the above code snippet if default _tags block is present, I want to convert the tags attribute value to `map[string]cty.Value` but can't figure out how?  Can you please suggest?
