### ISSUE TITLE
Default color for HCL in github/linguist

### ISSUE THREAD

**Issue by tuunit** [hashicorp/hcl#577]
Hi all,

as I don't know where else to ask for approval I would like to start the discussion here. I've noticed that the language list in [github/linguist](https://github.com/github/linguist) is missing a color for HCL.

https://github.com/github/linguist/blob/712a1ee719675c98be4edd5337c71862c50c4e30/lib/linguist/languages.yml#L2529-L2544

I would like to add the color which is currently used by GitHub itself when displaying HCL as part of a repository (#cccccc).
![image](https://user-images.githubusercontent.com/18513179/209915954-4380513f-2095-474f-a9cc-c8883015c0da.png)

I've already opened a PR for the necessary change:
https://github.com/github/linguist/pull/6231

**Comment by tuunit** [comment]
FYI
@liamcervante @alisdair @apparentlymart

**Comment by crw** [comment]
@tuunit thanks for bringing this to our attention! I'm going to run this past a few people and get back to you with a prefered color. Thanks again!

**Comment by crw** [comment]
@tuunit, The official answer is to go with `#844FBA` - you will find this to be a purple, not unlike the color associated with one of our open source projects. :)

**Comment by tuunit** [comment]
@crw sounds great!
