### ISSUE TITLE
Good tutorials to create your own DSL

### ISSUE THREAD

**Issue by swallace21** [hashicorp/hcl#603]
I am having a lot of fun experimenting with HCL, running into odd errors while wrapping my head around creating my DSL with HCL.

I am using hclsimple. I am often getting errors like this:
panic: unsuitable DecodeExpression target: no cty.Type for main.Attribute (no cty field tags)

Does anyone know of a good comprehensive learning resource?

**Comment by mlund01** [comment]
https://hcl.readthedocs.io/en/latest/go.html
