### ISSUE TITLE
Implementing fmt sub-commands for Terraform/etc

### ISSUE THREAD

**Issue by dcarley** [hashicorp/hcl#75]
Hi,

I'm looking at implementing a variant of @fatih's [hclfmt](https://github.com/fatih/hclfmt) with the differences that it would:

- be implemented as sub-commands/verbs in the utilities that use HCL e.g. `terraform fmt`. So that it would be easily available to users of those utilities without building/installing an additional binary
- follow the semantics of `go fmt` and `gofmt` a bit more closely, in that `terraform fmt` would rewrite all config files in your current PWD, but you could also provide list/write/diff/stdin arguments to change the behaviour
- configurable file extensions, e.g. `.hcl` or `.tf`

The intention is that most of the code would be implemented in the HCL project but wouldn't be specific to CLI. Then other utilities, such as Terraform and Nomad, could implement the CLI flags and pass over the necessary file extensions and options. The HCL project could also provide an `hclfmt` binary that works on `.hcl` files.

Does this sound sensible and useful? Would you like me to finish writing tests and submit a PR for this project and Terraform?

**Comment by fatih** [comment]
@dcarley hclfmt is based on hcl/printer. All the steps in your list can be easily done already with little changes :) hclfmt is just a wrapper around the `hcl/printer`. For example right now `hclfmt` checks if the file ends with `.hcl`, but the underlying `hcl/printer` package doesn't know it. It only accepts a single source file.

**Comment by dcarley** [comment]
That's essentially what I've done. I just wanted to double check that this was of interest to merge upstream and that the separation of concerns was correct.

Thanks for your work on the printer.

**Comment by dcarley** [comment]
Superseded by #80
