### ISSUE TITLE
Add links to implementations

### ISSUE THREAD

**Issue by dkrikun** [hashicorp/hcl#78]
Please, add links to HCL compliant parsers etc.
Vim plugin would be great too :+1: 

Thanks!

**Comment by wholroyd** [comment]
I wrote a language support extension for Visual Studio Code last weekend. Currently only a colorizer, hope to add intellisense and snippets to it soon.

https://marketplace.visualstudio.com/items/wholroyd.HCL

**Comment by VladRassokhin** [comment]
[There's plugin for IntelliJ Platform based IDEs](https://github.com/VladRassokhin/intellij-hcl) (IDEA, Android Studio, PyCharm, etc)
It has it's own Java lexer and parser autogenerated from .bnf and .flex files

**Comment by sethvargo** [comment]
Hi all,

We would gladly review a PR to link to implementations. Thanks!

**Comment by cpoole** [comment]
@dkrikun https://github.com/hashivim/vim-hashicorp-tools seems to work for vim
