### ISSUE TITLE
No write support for HCL?

### ISSUE THREAD

**Issue by rubenv** [hashicorp/hcl#8]
It feels like a strange omission not to include write-support for HCL. This decision was probably made with very good reasons but I have yet to discover them.

Making HCL read-only makes it an all-or-nothing thing: either a human writes the entire configuration file in HCL or the server writes it entirely in JSON (which renders it uneditable, or at least very clumsy, for a human).

The typical scenario I have in mind is a server that has a big configuration file with lots of bells and whistles. Some of these options are editable in the UI, while others are considered advanced and aren't exposed in the UI (because only 1% of the users would need them).

I don't see a way to make some variables machine-editable while maintaining an easy configuration language (for humans) for the more advanced options. One example of a configuration format that does support writing (and is reasonably readable) is the git configuration format.

Advice and recommendations are highly welcome. Let me know if none of this makes any sense, I'll happily clarify.

Perhaps what I'm doing just isn't part of the scope of HCL. I'd be cool with that too, I'll look for an alternative.

**Comment by mitchellh** [comment]
Done!

**Comment by savaki** [comment]
I see this is closed, but I don't see an Encode method.  Did this ever get merged into master?  Seems super useful and I'd love to be able to use it.

**Comment by mitchellh** [comment]
Hey @savaki, there is a hcl/writer package now that takes a raw AST and writes. We don't have a more easy to use `Encode` method yet.

**Comment by kvz** [comment]
Hey there, you can use the HCL printer (and `terraform fmt`) to do this now. @acconut and I took the liberty of wrapping a few of HashiCorp's libraries and release `json2hcl` (and hcl2json via `-reverse`) binaries for this. In the offchance this is still useful to somebody: https://github.com/kvz/json2hcl
