### ISSUE TITLE
decoder_test is incorrect

### ISSUE THREAD

**Issue by bsideup** [hashicorp/hcl#82]
https://github.com/hashicorp/hcl/blob/e3dcd7fc89f7749f704fc49092db63e6fd5ca2d7/decoder_test.go#L339

Decode is being used to decode expected JSON file, which is:
```
{
    "name": "terraform-test-app",
    "config_vars": {
        "FOO": "bar"
    }
}
```

This JSON file should create structure like this (native JSON decoder from "encoding/json"):
```
map[string]interface {}{
  "name": "terraform-test-app",
  "config_vars": map[string]interface {}{
    "FOO":"bar"
  }
}
```

But, in fact, we have:
```
map[string]interface {}{
  "name": "terraform-test-app",
  "config_vars": []map[string]interface {}{
    map[string]interface {}{
      "FOO":"bar"
    }
  }
}
```

**Comment by mitchellh** [comment]
This is correct: HCL doesn't match the native JSON encoder. 

The goal of HCL is to turn JSON into a similar (but nearly identical) structure as an HCL decode, not an `encoding/json` decode. Due to HCL's semantics of "blocks", we must turn maps into a slice of maps.
